# Using local node image to build the React app
image: node:12.18.0

# Announce the URL as per CRA docs
# https://create-react-app.dev/docs/advanced-configuration/
variables:
  PUBLIC_URL: /portfolio
  PRELIM_URL: "https://maxlepper.gitlab.io/portfolio/"
  LIVE_URL: "https://maxlepper.me"

# Name the stages involved in the pipeline
stages:
  - install
  - build
  - quality
  - optimize
  - deploy
  - audit

install:
  stage: install
  script:
    - echo "Installing dependencies"
    - npm install # Install all dependencies
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 60 mins
    paths:
      - node_modules/

build:
  stage: build
  script:
    - echo "Building"
    - CI=false npm run build #  CI=false will allow our build to complete with warnings
  artifacts:
    paths:
      - build
    expire_in: 60 mins

quality:jest:
  stage: quality
  script:
    - echo "Running tests"
    # CI=true will tell Jest to not run in watch mode
    # --env=jsdom provides a mock browser environment for testing
    # --coverage generates a human-readable summary of testing
    # --watchAll=false should force tests to run once, if CI=true doesn't
    - CI=true npm test -- --env=jsdom --coverage --watchAll=false
  dependencies:
    - install
  needs: ["install"] # Allows testing to begin running as soon as dependencies are installed
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  # Extracts the final overall coverage percentage. Also configured in gitlab for history
  allow_failure: true

optimize:
  stage: optimize
  script:
    - echo "Zipping up files pre-deployment"
    - gzip -k -9 $(find build -type f)
  artifacts:
    paths:
      - build
    expire_in: 60 mins
  dependencies:
    - build
  needs: ["build"] # Allows optimizing to begin running as soon as the build is complete
  only:
    - master
    - dev

# Job name for gitlab to recognise this results in assets for Gitlab Pages
# https://docs.gitlab.com/ee/user/project/pages/introduction.html#gitlab-pages-requirements
deploy:pages:
  stage: deploy
  script:
    - echo "Deploying Build to Preliminary (Pages)"
    - rm -rf public # Remove the existing public folder
    - cp -r build public # Copy build files to public dir for Gitlab Pages
  artifacts:
    paths:
      - public # The built files for Gitlab Pages to serve
    expire_in: 60 mins
  dependencies:
    - optimize
  only:
    - master
    - dev

# Deploy to Firebase
deploy:firebase:
  stage: deploy
  before_script:
    - npm install -g firebase-tools
  script:
    - (if [ -d "build" ]; then echo ok; else exit "No build folder found, try running pipeline again"; fi);
    - echo "Deploying build to Firebase"
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, commit $CI_COMMIT_TAG" --non-interactive --token $FIREBASE_DEPLOY_KEY
  artifacts:
    paths:
      - build
    expire_in: 60 mins
  dependencies:
    - optimize
  when: manual
  only:
    - master

# Conduct lighthouse audit on preliminary
lighthouse:pages:
  image: markhobson/node-chrome
  stage: audit
  before_script:
    - npm i -g lighthouse
  script:
    - lighthouse --chrome-flags="--headless --no-sandbox" $PRELIM_URL --output html --output-path ./report.html
  artifacts:
    paths:
      - ./report.html
    expire_in: 1 week
  needs: ["deploy:pages"]
  only:
    - master
    - dev
  allow_failure: true

# Conduct lighthouse audit on production
lighthouse:firebase:
  image: markhobson/node-chrome
  stage: audit
  before_script:
    - npm i -g lighthouse
  script:
    - lighthouse --chrome-flags="--headless --no-sandbox" $LIVE_URL --output html --output-path ./report.html
  artifacts:
    paths:
      - ./report.html
    expire_in: 1 week
  needs: ["deploy:firebase"]
  only:
    - master
  allow_failure: true
