# Using the node alpine image to build the React app
image: node:alpine

# Announce the URL as per CRA docs
# https://create-react-app.dev/docs/advanced-configuration/
variables:
  PUBLIC_URL: /portfolio

# Name the stages involved in the pipeline
stages:
  - deploy

# Job name for gitlab to recognise this results in assets for Gitlab Pages
# https://docs.gitlab.com/ee/user/project/pages/introduction.html#gitlab-pages-requirements
pages:
  stage: deploy
  script:
    - echo "Beginning deployment"
    - echo "Installing dependencies"
    - npm install # Install all dependencies
    - echo "Building for production"
    - npm run build # Build for production
    - echo "Build ready. Moving build to public"
    - rm -rf public # Remove the existing public folder
    - mv build public # Move build files to public dir for Gitlab Pages
    - echo "Build moved to public"
  artifacts:
    paths:
      - public # The built files for Gitlab Pages to serve
  only:
    - master # Only run on master branch
